# Generated by Django 3.0.5 on 2022-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220324_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='AgbiPRKw', max_length=8, null=True, unique=True),
        ),
    ]
